name: RequestLicense
on:
  workflow_dispatch:
  
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Request Activation File
        uses: uses: game-ci/unity-activate@v2.0.0
